### PR TITLE
add 30 day expiration policy to results bucket

### PR DESCRIPTION
**Pull request by calvinnhieu**

### CODE REVIEW

**Comment by calvinnhieu** [comment]
Good call! Will update README in this PR

**Comment by mckinsel** [comment]
I guess expanding on that a little, can a GET to `/matrix/{request_id}` give a response with a deleted s3 object?

**Comment by calvinnhieu** [comment]
Oh I see. I'll be addressing the API behavior wrt to expired matrices in the caching implementation/PR and don't plan on merging this before then (should've been more clear!).

**Comment by calvinnhieu** [comment]
Closing in favor of https://github.com/HumanCellAtlas/matrix-service/pull/382

**Pull request closed without merging**
