### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by brianraymor**
- [x] Add Table of Contents
- [x] Restore *Motivation and Challenges*
- [ ] Add User Stories
- [ ] Reference [Matrix Format](https://github.com/HumanCellAtlas/skylab/pull/129) in **File formats**
- [ ] Create documentation subdirectory for images and matrix format specification

### CODE REVIEW

**Comment by brianraymor** [comment]
This is still in progress. @calvinnhieu - I wanted to ensure that you were comfortable with me inlining *Motivations* and adding the ToC. I was also thinking about creating a documentation subdirectory for the .svg and the matrix output specification. @mckinsel - is it "safe" to snag your spec from that pending skylab PR? I'd like to add a reference in the **File formats** section of the README in the .zarr section.

**Comment by calvinnhieu** [comment]
@brianraymor Looks great - thanks for adding more context on the project. Definitely +1 on including _Motivation_ and a ToC, however, I'm less inclined to include the high level descriptions in _Challenges_ as the first thing people read. Do you think it makes sense to pull that section into another document? Also +1 on a subdirectory for docs.

**Comment by brianraymor** [comment]
Part of my motivation for adding the table of contents was to allow readers to skip ahead to their area of interest. @mckinsel  - what was the rationale for documenting the _Challenges_ in your original Motivations.md document? @calvinnhieu  - what are your thoughts about inlining our user stories in the README?

**Comment by calvinnhieu** [comment]
@brianraymor I see the value, but maybe not something as raw as "As an investigator, I would like to...". I think a few usage examples (closer to vignettes) would be great!

**Comment by brianraymor** [comment]
Closing this pull request. Will re-submit once the README has been updated to reflect the refactored architecture.

**Pull request closed without merging**
