### PR TITLE
Hella refactoring.

### PR DESCRIPTION
**Pull request by maniarathi**
Sorry, lint bothers me so I fixed all the lint errors in the repository.

Also alphabetized the requirements.

Also FYI: looks like there is one test that is failing currently.

### CODE REVIEW

**Comment by calvinnhieu** [comment]
Appreciate the thoroughness! For the record, I think we use different linters, but this is great (especially the alphabetization :+1: ). Thanks again.

**Comment by maniarathi** [comment]
> Thanks looks great. Which test was failing?

======================================================================
ERROR: test_parse_optimus (tests.unit.common.etl.transformers.test_cell_expression.TestCellExpressionTransformer)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/arathimani/CZI/matrix-service/tests/unit/common/etl/transformers/test_cell_expression.py", line 66, in test_parse_optimus
    bundle_manifest_path=os.path.abspath("tests/functional/res/etl/optimus_bundle_manifest.json")
  File "/Users/arathimani/CZI/matrix-service/matrix/common/etl/transformers/cell_expression.py", line 55, in _parse_from_metadatas
    cell_lines, expression_lines = self._parse_optimus_bundle(bundle_dir, bundle_manifest_path)
  File "/Users/arathimani/CZI/matrix-service/matrix/common/etl/transformers/cell_expression.py", line 229, in _parse_optimus_bundle
    n_cells = root.expression_matrix.cell_id.shape[0]
  File "/Users/arathimani/CZI/upload-service/venv/36/lib/python3.6/site-packages/zarr/hierarchy.py", line 353, in __getattr__
    return self.__getitem__(item)
  File "/Users/arathimani/CZI/upload-service/venv/36/lib/python3.6/site-packages/zarr/hierarchy.py", line 328, in __getitem__
    synchronizer=self._synchronizer, cache_attrs=self.attrs.cache)
  File "/Users/arathimani/CZI/upload-service/venv/36/lib/python3.6/site-packages/zarr/core.py", line 123, in __init__
    self._load_metadata()
  File "/Users/arathimani/CZI/upload-service/venv/36/lib/python3.6/site-packages/zarr/core.py", line 140, in _load_metadata
    self._load_metadata_nosync()
  File "/Users/arathimani/CZI/upload-service/venv/36/lib/python3.6/site-packages/zarr/core.py", line 168, in _load_metadata_nosync
    self._compressor = get_codec(config)
  File "/Users/arathimani/CZI/upload-service/venv/36/lib/python3.6/site-packages/numcodecs/registry.py", line 36, in get_codec
    raise ValueError('codec not available: %r' % codec_id)
ValueError: codec not available: 'blosc'

----------------------------------------------------------------------

**Comment by maniarathi** [comment]
Tried installing blosc and also numcodecs but neither worked so I gave up.

**Comment by mckinsel** [comment]
Ah thanks. Yeah depending on your environment, you can `pip install numcodecs` and it will "succeed" but not build blosc.

**Pull request merged**
