### PR TITLE
remove glioblastoma bundles from tests

### PR DESCRIPTION
**Pull request by calvinnhieu**
Functional tests passing (dev, integration)

### CODE REVIEW

**Comment by mckinsel** [comment]
Looks good, what did you replace them with?

**Comment by calvinnhieu** [comment]
Latest test SS2 bundles in integration. I believe they're whitelisted @parthshahva

**Comment by mckinsel** [comment]
Is there anything in a cache or results bucket we need to delete?

**Comment by calvinnhieu** [comment]
Ah, yeah. We should clear the predev, dev and integration caches and results buckets - I'll do that now

**Comment by mckinsel** [comment]
Thank you!

**Comment by calvinnhieu** [comment]
Cleared

**Pull request merged**
