### PR TITLE
Enable .mtx and .csv formats

### PR DESCRIPTION
**Pull request by calvinnhieu**
Tested on predev environment

.mtx (https://github.com/HumanCellAtlas/matrix-service/issues/39):
Results on predev: https://s3.amazonaws.com/dcp-matrix-service-results-predev/dae8194f299ada5284442893ead8b8f49b4f29a8d8a7f2e9c513e9971378c628.mtx.gz

.csv (https://github.com/HumanCellAtlas/matrix-service/issues/59):
Results on predev: https://s3.amazonaws.com/dcp-matrix-service-results-predev/7da730847f594d33c136c84d4d0701adedbe6933f2c1783435452595a5be9502.csv.gz

### CODE REVIEW

**Comment by calvinnhieu** [comment]
@mckinsel Could you verify the output results?

**Comment by mckinsel** [comment]
Hey the output from `mtx` is actually a gzipped tarball. Should we change the format name to reflect that?

**Comment by calvinnhieu** [comment]
Not sure. For consistency with the other format names I want to keep it the same, but for clarity/UX it makes sense to change the input to something like `mtx.gz`. Do you think this would cause confusion if we don't change it? Note that the `matrix_location` URL is updated to return `mtx.gz`

**Comment by mckinsel** [comment]
I think a user would end up doing something like `wget https://somethingsomething.mtx` and then have  a local file with an mtx extension that they need to unzip and untar. That would probably be a surprise.

**Comment by brianraymor** [comment]
It's surprising that there's not a standard for tar.gz. Pick your adventure: https://superuser.com/questions/901962/what-is-the-correct-mime-type-for-a-tar-gz-file 

In the wget scenario, even if we advertised *mtx+gzip*, users on Windows are going to be surprised by the .tar format unless they've installed cygwin?

**Comment by mckinsel** [comment]
Maybe we should just zip it, and then call it `mtx.zip`?

**Comment by brianraymor** [comment]
I like *mtx+gzip* a'la - https://tools.ietf.org/html/rfc8460#section-6.3 but I appreciate it's a [bike shed](http://bikeshed.com/).

**Comment by calvinnhieu** [comment]
@mckinsel That sounds good - it's simple, works on Windows and achieves the same thing as tar and gz. Does it make sense to also use zip for csv? Also if we're compressing loom files, we should update the return file extension to reflect that (I'm not sure if we are)

**Comment by mckinsel** [comment]
So zip is what the Single Cell Expression Atlas does, so I'd lean toward that. @brianraymor I'm not sure where we'd set the content-type. Do you mean when we put the object in s3?

**Comment by brianraymor** [comment]
What Content-Type(s) are returned when a client GETs the *matrix_location* URL?

**Comment by calvinnhieu** [comment]
@brianraymor Looks like `binary/octet-stream`
screen shot 2018-11-19 at 4 42 15 pm

**Comment by mckinsel** [comment]
Pretty sure that's just the default. We can set it when we PUT.

**Pull request merged**
